### ISSUE TITLE
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-101.pkl not found!

### ISSUE THREAD

**Issue by ZiyeHu** [MegviiDetection/FSCE#15]
python tools/train_net.py --num-gpus 8 \
        --config-file configs/PASCAL_VOC/base-training/R101_FPN_base_training_split1.yml

**Comment by Chauncy-Cai** [comment]
You can follow this issue.
https://github.com/ucbdrive/few-shot-object-detection/issues/87#issuecomment-768988092
You can also use your own pretrained weight by changing MODEL.WEIGHTS in yaml.

**Comment by Ze-Yang** [comment]
`pip install fvcore==0.1.2.post20201020` will address the problem.
