### ISSUE TITLE
runtinmeError:Not compiled with GPU support 

### ISSUE THREAD

**Issue by john2020-210** [MegviiDetection/FSCE#16]
When I run the code ,I met the following problem" RuntinmeError:Not compiled with GPU support " dose anyone  meet the same problem? my environment is pytorch1.71 cuda 10.1 GRX 2080Ti

**Comment by bsun0802** [comment]
Try pytorch 1.4, and build again. 

To get started, maybe you can start with fsdet(https://github.com/ucbdrive/few-shot-object-detection) to see if you can get it to run first.

**Comment by john2020-210** [comment]
@bsun0802 Thanks for your reply.I have tried with pytorch1.4 and started the fsdet successfully ,but it still report the RuntimeError:Not compiled with GPU support(ROIAlign_forward at FSCE-main /fsdet/layers/csrc/ROIAlign/ROIAlign.h:73

**Comment by bsun0802** [comment]
Maybe you can delete it and try build again? I'm no expert in build, ours use the same build code from fsdet. 

It seems other people were able to run our code. Maybe you can find information in other issues?

**Comment by john2020-210** [comment]
Thank you all the same，I find the error  mainly relates to the  ROIAlign_forward in fsdet/layers/csrc/ROIAlign/ROIAlign.73,could you help me ?

**Comment by bsun0802** [comment]
ROIAlign as you mentioned, are C source files and I believe coming from detectron2, and we do not modify and we believe fsdet's author will not modify ROI Align as well. 

Sorry but I have no idea bro haha.
