### ISSUE TITLE
Variants about MoCo and Prototype

### ISSUE THREAD

**Issue by Chen-Song** [MegviiDetection/FSCE#17]
In your code, there are some variants based on MoCo ("eg, ContrastiveROIHeadsWithStorage") or Prototype ("eg, ContrastiveROIHeadsWithPrototype"). What is the final result (nAP) of these two variants? Will it be much lower than the optimal result reported in the paper?

**Comment by bsun0802** [comment]
The prototype turns out to be not helping. 

The momentum encoding seems to be a bit lower than reported in the paper, tested on VOC Split 1 and get nAP=61+. But the code might not be necessary with the one uploaded here (shouldn't have uploaded those ..).

**Comment by Chen-Song** [comment]
In your code:
`_C.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.PROTOTYPE.PATH = ''
self.prototype_path              =  cfg.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.PROTOTYPE.PATH
prototype_tensor = torch.load(self.prototype_path)  # [num_classes+1, 1024]`

Is PROTOTYPE.PATH empty?

**Comment by Chen-Song** [comment]
In your code:
_C.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.PROTOTYPE.PATH = '' 
self.prototype_path = cfg.MODEL.ROI_BOX_HEAD.CONTRASTIVE_BRANCH.PROTOTYPE.PATH 
prototype_tensor = torch.load(self.prototype_path) # [num_classes+1, 1024]


Is PROTOTYPE.PATH empty?
