### ISSUE TITLE
Contrastive Proposal Encoding (CPE) Loss is not used for shot1 and 2 on the Pascal dataset？

### ISSUE THREAD

**Issue by xiaoliqiangxxqzz** [MegviiDetection/FSCE#18]
It's nice to see the interesting work the authors are doing on Fewshot！
But from the configuration files provided with the code you can see that Shot1 and 2 did not unfreeze FPN and RPN and did not use the CPE loss proposed by the authors.

I don't know if it's because the authors forgot to release the corresponding configuration files for Shot1 and 2, or if the results reported in the paper are only fine-tuning based on TFA.

Hope the author can answer, thanks!!!

@bsun0802

**Comment by bsun0802** [comment]
Yes, it is not applied on the shots you mentioned. 

Reason: 
1. For extremely low shot, I don't want to go harsh on any possible positive samples. 
2. When a complexer model does not help, stick to a simple one :shipit:. (Occam's razor Principle)
