### ISSUE TITLE
failed when building

### ISSUE THREAD

**Issue by jinweiLiu** [MegviiDetection/FSCE#19]
When running the command "python setup.py build develop", I got an error--command 'gcc' failed with exit status 1. How can I fix it? Dose it means the version of gcc is not right?

**Comment by huhan233** [comment]
I have the same question.If you solve this problem,I hope you could tell me how do you solve it. THANK YOU!

**Comment by JJ-res101** [comment]
I also have the same question!

**Comment by csliuchang** [comment]
I also have the same question!

**Comment by manikandan-ravikiran** [comment]
Looks like pytorch post 1.4 issue. Install with version 1.4 it builds well

**Comment by natures66** [comment]
> Looks like pytorch post 1.4 issue. Install with version 1.4 it builds well

I downgrade my pytorch version then it works

**Comment by DrizzleSh** [comment]
what if my GPU don't support cuda below 11.0?

**Comment by qjh666888** [comment]
@DrizzleSh 请问你解决了吗
