### ISSUE TITLE
CPE loss is not used for MS COCO dataset?

### ISSUE THREAD

**Issue by chenf99** [MegviiDetection/FSCE#20]
Thanks for the great work you have done on few-shot detection!
From the config file you provided, I found that you didn't use CPE loss on MS COCO dataset. Does it mean that FSCE is just a strong baseline on MS COCO dataset?
Besides, I can't reproduce the result on MS COCO dataset, I got 11.59 (just on seed 0) while in paper the result is 11.9.
I used the base train checkpoint from [http://dl.yf.io/fs-det/models/coco/base_model/model_final.pth](http://dl.yf.io/fs-det/models/coco/base_model/model_final.pth). Could you please check the config file? Thank you!

**Comment by bsun0802** [comment]
Yes, the gain of CPE on MS COCO is very marginal, and we provide the baseline here only in this repo.
