### ISSUE TITLE
Where is the requirement.txt?

### ISSUE THREAD

**Issue by maoyw57** [MegviiDetection/FSCE#35]
I can't find where is the requirement.txt.
And I meet a problem about build fsdet in Windows.
![image](https://user-images.githubusercontent.com/73291365/125619327-b6eafaf7-b5f2-41f3-89ad-f2114103da63.png)
![image](https://user-images.githubusercontent.com/73291365/125619375-a02380d7-1fc6-4f6c-8b0e-06c83af05f09.png)
Could you help me about this problem?

**Comment by fedi112** [comment]
Did you find the solution for the requirements.txt file ?
