### ISSUE TITLE
Code  about  'double the maximum number of proposals kept after NMS '

### ISSUE THREAD

**Issue by Wei-i** [MegviiDetection/FSCE#40]
Thanks for your great work and source code ：）
I am confused about where the code  refers to 'double the maximum number of proposals kept after NMS'.
The default configuration of `_C.MODEL.RPN.POST_NMS_TOPK_TRAIN`  is 2000, so in my view, FSCE should set `_C.MODEL.RPN.POST_NMS_TOPK_TRAIN` as 4000.
However, for example, in `FSCE/fsdet/config/defaults.py`:

```python
MODEL:
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

```

am I wrong?
I would be grateful if you could help me :)

**Comment by joy-yjl** [comment]
> Thanks for your great work and source code ：） I am confused about where the code refers to 'double the maximum number of proposals kept after NMS'. The default configuration of `_C.MODEL.RPN.POST_NMS_TOPK_TRAIN` is 2000, so in my view, FSCE should set `_C.MODEL.RPN.POST_NMS_TOPK_TRAIN` as 4000. However, for example, in `FSCE/fsdet/config/defaults.py`:
> 
> ```python
> MODEL:
>   RPN:
>     POST_NMS_TOPK_TRAIN: 2000
> ```
> 
> am I wrong? I would be grateful if you could help me :)

 I get the same question. Have you  figured it out?
