### ISSUE TITLE
built error

### ISSUE THREAD

**Issue by zzzzjx** [MegviiDetection/FSCE#41]
I met the  error:  NotADirectoryError: [Errno 20] Not a directory: '/home/FSCE/fsdet/model_zoo/configs'
 when I run python setup.py build develop, how can I solve it ? Waiting for your reply!

**Comment by LLLLL13579** [comment]
I have the same problem, but the configs file is under the folder.
If you solve it, please let me know. Thank you.

**Comment by HengYuD** [comment]
You can use 'll /home/FSCE/fedet/model_zoo/configs' to see more details. You could just delete it and rebuild it.
