### ISSUE TITLE
Schedule of shot3, shot5, shot10 of pascal voc.

### ISSUE THREAD

**Issue by Retiina** [MegviiDetection/FSCE#7]
Sir, I cannot find the baseline config for pascal voc shot3, shot5, shot10, I guess the only change is the training schedule, could you tell me the schedule of them. Thanks in advance!

**Comment by bsun0802** [comment]
We used the same training steps for baseline and contrastive training. Simply change the contrastive head we provided for shot3/5/10 to a default standard RoI head, then you get the baseline config.

**Comment by Retiina** [comment]
Thanks for your quick replay!

**Comment by Retiina** [comment]
@bsun0802 , Sir, may I ask where is the config of FSCE coco shot10, I can only find the baseline? Thank you!

**Comment by bsun0802** [comment]
We are not satisfied with the COCO performance, its only marginal compared to the strong baseline. We encourage people to research from the COCO baseline :raised_hands:. We are working on a v2 as well.

**Comment by Retiina** [comment]
Sir, thanks for you quick reply, cheer up!

**Comment by Retiina** [comment]
@bsun0802 Excuse me, where can I find the coco novel instance json that used in the paper?

**Comment by bsun0802** [comment]
http://dl.yf.io/fs-det/datasets/
