### ISSUE TITLE
Inconsistent setting of shot 1, 2 and 3, 5, 10

### ISSUE THREAD

**Issue by Retiina** [MegviiDetection/FSCE#8]
Dear author, I like your project very much. But I find that there exist inconsistent setting between shot1, 2 and 3, 5, 10, for examples,

In split1, shot1, pascal voc, FPN and RPN are frozen,
https://github.com/MegviiDetection/FSCE/blob/ad6dbd06ceb1473ba6f1c1709e1365dfb4161e2f/configs/PASCAL_VOC/split1/1shot_baseline.yml#L9-L16

But in split 1, shot3, pascal voc, FPN and RPN are unfrozen,
https://github.com/MegviiDetection/FSCE/blob/ad6dbd06ceb1473ba6f1c1709e1365dfb4161e2f/configs/PASCAL_VOC/split1/3shot_CL_IoU.yml#L9-L16.

Besides, in split1, shot1, pascal voc, test aug are disabled,
https://github.com/MegviiDetection/FSCE/blob/ad6dbd06ceb1473ba6f1c1709e1365dfb4161e2f/configs/PASCAL_VOC/split1/1shot_baseline.yml#L44-L45

However in split1, shot3, pascal voc, test aug are enabled,
https://github.com/MegviiDetection/FSCE/blob/ad6dbd06ceb1473ba6f1c1709e1365dfb4161e2f/configs/PASCAL_VOC/split1/3shot_CL_IoU.yml#L55-L58

I am really puzzled about that. Could you explain it to me? Thanks in advance!

**Comment by bsun0802** [comment]
AFAIK, the Test Aug does not matter, you can delete that and see if the results are roughly the same. 

For low shot, unfreezing all parts as in 5/10-shot incurs over-fitting and decrease the performance a bit. If you want consistency, sacrifice the performance for low shot a little. We report the best performance we can achieve here.  

P.S., I personally think the current few-shot dataset are still naive and not flawless. I personally DO NOT think one can pursue an algorithm which is optimal for both  1-shot and few-shot with exact same settings.
