### ISSUE TITLE
AssertionError: get_event_storage() has to be called inside a 'with EventStorage(...)' context!

### ISSUE THREAD

**Issue by LJC-GitHub** [MegviiDetection/FSCE#9]
when evaluating the trained models...  
please tell me how to solve it，thanks！
![image](https://user-images.githubusercontent.com/41890030/112242663-4588d100-8c87-11eb-8a55-8969a0951e9a.png)

**Comment by LJC-GitHub** [comment]
I have solved this problem

**Comment by LJC-GitHub** [comment]
I avoid related errors by replacing the following sentences. If there is a better solution, you can tell me, thank you! （decay_rate may be 0.25）

![image](https://user-images.githubusercontent.com/41890030/112279381-d4fda680-8cbe-11eb-81c4-42017b4b3fe4.png)

![image](https://user-images.githubusercontent.com/41890030/112279244-ad0e4300-8cbe-11eb-8609-ae3429d22836.png)

**Comment by Retiina** [comment]
```
if self.training:
    ...
```

**Comment by LJC-GitHub** [comment]
> ```
> if self.training:
>     ...
> ```

**Comment by LJC-GitHub** [comment]
> ```
> if self.training:
>     ...
> ```

Thank you for your answers, when evaluating the trained models, the process really has nothing to do with contrast _loss_weight

**Comment by LJC-GitHub** [comment]
Thank you for your answers, when evaluating the trained models, the process really has nothing to do with contrast _loss_weight

**Comment by LJC-GitHub** [comment]
> ```
> if self.training:
>     ...
> ```

Thank you for your answers, when evaluating the trained models, the process really has nothing to do with contrast _loss_weight

**Comment by LJC-GitHub** [comment]
![image](https://user-images.githubusercontent.com/41890030/112300004-5828f780-8cd3-11eb-9e05-fa630ad64384.png)
It works.
